import { t as msg } from '../i18n/runtime.ts';
import type { HelpCard } from './cards';

// Explicit help IDs are independent of tour anchors and UI wording.
// Shared controls may reuse a concept; each group still has its own card.
const card = (title: string, text: string, how?: string, example?: string): HelpCard => ({ title, text, how, example });
export const EXPLANATIONS: Record<string, HelpCard> = {
  get 'drum-rack'() { return card(msg('rack.title'), msg('rack.help'), msg('rack.how')); },
  get 'rack-hit'() { return card(msg('rack.hitTitle'), msg('rack.hitHelp'), msg('rack.hitHow')); },
  get 'rack-duplicate'() { return card(msg('rack.duplicate'), msg('rack.duplicateHelp')); },
  get 'rack-reorder'() { return card(msg('rack.reorder'), msg('rack.reorderHelp')); },
  get 'rack-volume'() { return card(msg('rack.level'), msg('rack.volumeHelp')); },
  get 'rack-pan'() { return card(msg('trackRow.pan'), msg('rack.panHelp')); },
  get 'rack-remove'() { return card(msg('rack.remove'), msg('rack.removeHelp')); },
  get 'playback-toggle'() { return card(msg('range.title'), msg('range.toggleHelp')); },
  get 'playback-start'() { return card(msg('range.play'), msg('range.playHelp')); },
  get 'playback-move'() { return card(msg('range.move'), msg('range.moveHelp')); },
  get 'playback-a'() { return card(msg('range.start'), msg('range.startHelp')); },
  get 'playback-b'() { return card(msg('range.end'), msg('range.endHelp')); },
  get 'playback-undo'() { return card(msg('range.undo'), msg('range.undoHelp')); },
  get 'playback-cycle'() { return card(msg('range.cycle'), msg('range.cycleHelp')); },
  get 'playback-panel'() { return card(msg('range.panel'), msg('range.panelHelp')); },
  get 'rack-merge'() { return card(msg('rack.mergeTitle'), msg('rack.mergeHelp')); },
  get 'rack-import'() { return card(msg('rack.import'), msg('rack.importHelp')); },
  get 'rack-export'() { return card(msg('rack.export'), msg('rack.exportHelp')); },
  get 'playback-range'() { return card(msg('range.title'), msg('range.help')); },
  get 'playback-ruler'() { return card(msg('range.title'), msg('range.rulerHelp')); },
  get 'playback-variations'() { return card(msg('range.fixed'), msg('range.fixedHelp')); },
  get language() { return card(msg('language.title'), msg('language.text'), msg('language.how')); },
  get 'sound-workshop'() { return card(msg("explanations.soundWorkshop"), msg("explanations.turnARecordingIntoAPortableInstrument"), msg("explanations.advancedActionsAreSeparateSourceSeparationAnd")); },
  get 'workshop-region'() { return card(msg("explanations.selectARegion"), msg("explanations.dragAcrossTheWaveformOrEnterExact"), msg("explanations.openRecordingsUpTo32MiBAnd")); },
  get 'workshop-root'() { return card(msg("explanations.regionRootFrequency"), msg("explanations.theOriginalNoteSPitchInHertz"), msg("explanations.detectEstimatesAStablePeriodNearThe")); },
  get 'workshop-separate'() { return card(msg("explanations.sourceSeparation"), msg("explanations.demucsThroughFalAiSeparatesVocalsDrums"), msg("explanations.thisActionSendsTheSelectedRegionTo")); },
  get 'workshop-model'() { return card(msg("explanations.approximateSoundModel"), msg("explanations.buildEightHarmonicFramesAndAnAmplitude"), msg("explanations.setTheRootFrequencyAndCompareThe")); },
  get 'learning-studio'() { return card(msg("explanations.learningStudio"), msg("explanations.twoPathsACompleteIDMMiniatureWith"), msg("explanations.startingALearningCopyFirstStoresYour")); },
  get 'learning-compare'() { return card(msg("explanations.beforeAndAfterComparison"), msg("explanations.rememberACapturesTheCurrentPatchIn"), msg("explanations.switchingStopsPlaybackListenToBothVersions")); },
  get 'wave-import'() { return card(msg("explanations.importAWavetable"), msg("explanations.theWAVMustContainConsecutiveCyclesOf"), msg("explanations.select28EvenlySpacedFramesFrom")); },
  get 'va-pwm'() { return card(msg("explanations.pulseWidthModulation"), msg("explanations.pwmChangesTheFractionOfEachPeriod"), msg("explanations.amountSetsTheDeviationFromTheChosen")); },
  get 'va-drift'() { return card(msg("explanations.slowPitchDrift"), msg("explanations.gentlePitchMovementInCents100Cents"), msg("explanations.try13CentsEachUnisonVoice")); },
  get 'voice-processing'() { return card(msg("explanations.singleVoiceProcessing"), msg("explanations.setEffectsAndThePlayingRangeFor"), msg("explanations.theseSettingsAreSavedWithTheInstrument")); },
  get 'voice-range'() { return card(msg("explanations.voiceRange"), msg("explanations.theVoicePlaysOnlyWhenBothNote"), msg("explanations.assignLowNotesToOneVoiceHigh")); },
  get 'voice-effects'() { return card(msg("explanations.voiceEffects"), msg("explanations.upToFourEffectsInSequenceFor"), msg("explanations.delayRepeatsTheSoundFeedbackExtendsThe")); },
  get 'portable-packs'() { return card(msg("explanations.portableInstrumentPacks"), msg("explanations.aNamedArchiveContainingSeveralInstrumentsAnd"), msg("explanations.createAPackOrOpenAnExisting")); },
  get 'pack-file'() { return card(msg("explanations.openAPack"), msg("explanations.chooseABarlowPackZipFileAnd"), msg("explanations.afterValidationSelectTheInstrumentsToAdd")); },
  get 'pack-metadata'() { return card(msg("explanations.packNameAndDescription"), msg("explanations.aNameHelpsIdentifyThePackIts"), msg("explanations.metadataTravelsWithTheArchiveAndIs")); },
  get 'pack-selection'() { return card(msg("explanations.packContents"), msg("explanations.select164InstrumentsSearchNarrowsThe"), msg("explanations.importPreviewsANewNameOnThe")); },
  get 'pack-transfer'() { return card(msg("explanations.transferSelectedInstruments"), msg("explanations.exportCreatesOneArchiveAndStoresShared"), msg("explanations.progressReflectsValidationAndPackingStagesCancel")); },
  get 'scene-space'() { return card(msg("explanations.sharedSceneReverb"), msg("explanations.oneReverbForTheWholeProjectEach"), msg("explanations.enableSharedReverbInTheMasterAnd")); },
  get 'automation-record'() { return card(msg("explanations.recordParameterMovement"), msg("explanations.duringPlaybackRecordManualMovementOfThe"), msg("explanations.startRecordingMoveTheControlThatAppears")); },
  get 'automation-record-value'() { return card(msg("explanations.recordedParameterValue"), msg("explanations.0100IsANormalizedScaleFor"), msg("explanations.theKnobAppearsDuringRecordingDoubleClick")); },
  get 'equalizer'() { return card(msg("explanations.equalizer"), msg("explanations.shapeTheFrequencyBalanceRemoveRumbleMake"), msg("explanations.selectABandShapeAndFrequencyStart")); },
  get 'eq-graph'() { return card(msg("explanations.frequencyResponse"), msg("explanations.lowFrequenciesAreOnTheLeftHigh"), msg("explanations.theGraphIsCalculatedAt48KHz")); },
  get 'eq-band'() { return card(msg("explanations.eqBands"), msg("explanations.eachNumberSelectsASeparateProcessingBand"), msg("explanations.forExampleOneBandRemovesLowRumble")); },
  get 'eq-band-enabled'() { return card(msg("explanations.enableABand"), msg("explanations.temporarilyRemoveThisBandFromProcessingWhile"), msg("explanations.compareWithAndWithoutItsCorrectionOther")); },
  get 'eq-shape'() { return card(msg("explanations.bandShape"), msg("explanations.bellChangesARegionAroundItsCenter"), msg("explanations.cutFiltersRemoveUnwantedSpectrumEdgesBell")); },
  get 'eq-frequency'() { return card(msg("explanations.bandFrequency"), msg("explanations.bellCenterFrequencyOrAShelfCut"), msg("explanations.turnTheKnobWhileListeningToThe")); },
  get 'eq-gain'() { return card(msg("explanations.bandGain"), msg("explanations.positiveDecibelsBoostTheRegionNegativeDecibels"), msg("explanations.smallChangesHelpWithMixingStrongBoosts")); },
  get 'eq-q'() { return card(msg("explanations.qBandwidthAndResonance"), msg("explanations.forABellHigherQNarrowsThe"), msg("explanations.useANarrowBellForAResonance")); },
  get 'eq-bypass'() { return card(msg("explanations.bypassEQ"), msg("explanations.disableTheEntireEqualizerWhileKeepingIts"), msg("explanations.compareByEarAtSimilarLoudnessPress")); },
  get 'playback-settings'() { return card(msg("explanations.repeatableSound"), msg("explanations.randomElementsNormallyVaryBetweenRunsRepeatable"), msg("explanations.keepOneSeedWhenComparingEditsAnd")); },
  get 'theme'() { return card(msg("explanations.lightTheme"), msg("explanations.changeTheAppearanceOfWorkAreasGraphs"), msg("explanations.enableLightThemeInSettingsForA")); },
  get 'main-menu'() { return card(msg("explanations.mainMenu"), msg("explanations.applicationCommandsForFilesEditHistoryWork"), msg("explanations.tabFocusesTheMenuArrowsChooseA")); },
  get 'track-effects'() { return card(msg("explanations.trackEffects"), msg("explanations.aProcessingChainSharedByAllClips"), msg("explanations.addAnEffectAndAdjustItsParameters")); },
  get 'panel-switches'() { return card(msg("explanations.showOrHidePanels"), msg("explanations.aHighlightedButtonMeansItsPanelIs"), msg("explanations.pressAgainToFreeUpSpaceOnly")); },
  get 'sketch-muted'() { return card(msg("explanations.trackMutedInThisScene"), msg("explanations.soundIsMutedButTheClipS"), msg("explanations.releaseMToResumeTheCurrentClip"), msg("explanations.dropTheBassForAFewBars")); },
  get 'mseg-target'() { return card(msg("explanations.whatChangesDuringANote"), msg("explanations.amplitudePitchAndLocalFilterHaveIndependent"), msg("explanations.startWithAmplitudeThenAddAPitch")); },
  get 'mseg-listen'() { return card(msg("explanations.auditionTheResult"), msg("explanations.playANoteWithAllEnabledEnvelopes")); },
  get 'mseg-pitch'() { return card(msg("explanations.pitchBreakpoints"), msg("explanations.raiseOrLowerPitchRelativeToThe"), msg("explanations.tryARampUpWith2Octaves")); },
  get 'mseg-filter'() { return card(msg("explanations.localFilterBreakpoints"), msg("explanations.eachNoteAndLayerHasItsOwn"), msg("explanations.forANoiseRiserTryA400")); },
  get 'mseg-depth'() { return card(msg("explanations.modulationAmountInOctaves"), msg("explanations.theGraphLevelMultipliesTheAmountZero"), msg("explanations.doubleClickTheKnobForNumericInput")); },
  get 'mseg-filter-base'() { return card(msg("explanations.localFilterBaseFrequency"), msg("explanations.cutoffAtZeroEnvelopeLevelWith2")); },
  get 'mseg-control'() { return card(msg("explanations.breakpointMovement"), msg("explanations.theLineControlsPitchOrFilterMovement"), msg("explanations.thisShapeDoesNotExtendTheSound")); },
  get 'mseg-control-level'() { return card(msg("explanations.modulationLevel"), msg("explanations.zeroMeansTheBaseFrequency100Means"), msg("explanations.toRiseFromALowPitchTo")); },
  get 'mseg-curve'() { return card(msg("explanations.incomingSegmentCurve"), msg("explanations.shapeTheTransitionFromThePreviousPoint"), msg("explanations.selectThePointToTheRightOf")); },
  get 'mseg-duration'() { return card(msg("explanations.envelopeTimeScale"), msg("explanations.withoutSustainThisIsTheFallbackDuration"), msg("explanations.forExampleA1SScaleWith")); },
  get 'mseg-playback'() { return card(msg("explanations.howTheEnvelopeFollowsANote"), msg("explanations.stretchTheWholeShapeToTheNote"), msg("explanations.useSustainForHeldSoundsIfThe")); },
  get 'mseg-sustain'() { return card(msg("explanations.sustainPoint"), msg("explanations.reachThisPointAtTheSpeedSet"), msg("explanations.chooseAnInteriorPointNoneStretchesThe")); },
  get 'mseg-loop'() { return card(msg("explanations.pingPongLoop"), msg("explanations.insteadOfHoldingStillTheEnvelopeTravels"), msg("explanations.forPulsationChooseALowerLevelPoint")); },
  get 'mseg-loop-start'() { return card(msg("explanations.loopStart"), msg("explanations.theLeftBoundaryOfTheSegmentEnding"), msg("explanations.chooseAnyEarlierPointDeletingThisBoundary")); },
  get 'mseg-loop-repeats'() { return card(msg("explanations.repeatsPerNote"), msg("explanations.oneRepeatIsAFullBackwardAnd"), msg("explanations.try12ForASlowBreathing")); },
  get 'layer-source-editor'() { return card(msg("explanations.layerSourceEditor"), msg("explanations.editOnlyTheSelectedAdditionalVoiceOperators"), msg("explanations.useTheSameSoundControlsAsThe"), msg("explanations.buildABassFromASineSub")); },
  get 'layer-audition-solo'() { return card(msg("explanations.auditionOnlyThisLayer"), msg("explanations.hearTheSelectedVoiceWithItsLevel"), msg("explanations.compareWithTheFullInstrumentSumNormalization")); },
  get 'layer-filter-base'() { return card(msg("explanations.layerFilterEnvelopeBase"), msg("explanations.frequencyThisVoiceSLocalFilterSettles"), msg("explanations.forAPluckUsePositiveAmountAnd")); },
  get 'wave-gesture'() { return card(msg("explanations.waveformInteraction"), msg("explanations.dragToSelectARegionInA"), msg("explanations.zoomIntoThePartYouNeedAll")); },
  get 'instrument-export'() { return card(msg("explanations.instrumentInOneFile"), msg("explanations.saveThisSoundWithItsRecordingsLayers"), msg("explanations.shareTheFileWithAnotherBarlowUser")); },
  get 'instrument-import'() { return card(msg("explanations.importAnInstrumentFile"), msg("explanations.validateABarlowArchiveAndAddThe"), msg("explanations.chooseAFileReviewTheNameAnd")); },
  get 'instrument-import-cancel'() { return card(msg("explanations.cancelFileValidation"), msg("explanations.cancelBeforeAddingToTheLibraryThe"), msg("explanations.onceInstallationStartsWaitForItTo")); },
  get 'scene-chip'() { return card(msg("explanations.sceneASectionOfThePiece"), msg("explanations.clickToSelectASceneDragTo"), msg("explanations.typeANameAndPressEnterEscape")); },
  get 'scene-delete'() { return card(msg("explanations.deleteCurrentScene"), msg("explanations.deleteTheSelectedSceneAndItsEntries"), msg("explanations.ctrlZRestoresTheDeletedScene")); },
  get 'scene-chain'() { return card(msg("explanations.showSceneSequence"), msg("explanations.showOrHideTheOrderAndDuration"), msg("explanations.arrangeDevelopmentAndAFinaleThenSelect")); },
  get 'automation-mods'() { return card(msg("explanations.parameterMovement"), msg("explanations.aDrawnCurveChangesAParameterOver"), msg("explanations.modulationIsDrawnAsADashedLine")); },
  get 'track-filters'() { return card(msg("explanations.whichTracksToShow"), msg("explanations.filtersRemoveTracksFromViewWithoutChanging"), msg("explanations.combineNameSearchWithHidingMutedTracks")); },
  get 'track-filter-name'() { return card(msg("explanations.findATrackByName"), msg("explanations.showTracksWhoseNamesContainTheQuery"), msg("explanations.typePartOfABassTrackS")); },
  get 'track-filter-muted'() { return card(msg("explanations.hideTracksMutedInThisScene"), msg("explanations.hideTracksWhoseSlotsAreMutedIn"), msg("explanations.thisOnlyFiltersTheViewItDoes")); },
  get 'track-filter-reset'() { return card(msg("explanations.showEveryTrack"), msg("explanations.clearTheNameSearchAndDisableHiding"), msg("explanations.useThisToFindATrackMissing")); },
  get 'operator-tail'() { return card(msg("explanations.operatorRingingTail"), msg("explanations.timeForThisPartialToDecayBy"), msg("explanations.giveBellPartialsDifferentTailsHighOvertones")); },
  get 'mod-rate'() { return card(msg("explanations.rateOfChange"), msg("explanations.howQuicklyAnEffectOrModulationOscillates"), msg("explanations.slowRatesCreateGradualMovementFastRates")); },
  get 'help-search'() { return card(msg("explanations.findAnExplanationAndControl"), msg("explanations.searchHelpAndGuidesIncludingCurrentlyHidden"), msg("explanations.chooseSearchHelpOrPressCtrlEnter")); },
  get 'help-search-query'() { return card(msg("explanations.whatToSearchFor"), msg("explanations.enterATermSuchAsPortamentoOr")); },
  get 'help-search-results'() { return card(msg("explanations.searchResults"), msg("explanations.selectAResultOnTheLeftTo")); },
  get 'help-search-article'() { return card(msg("explanations.explanationAndPath"), msg("explanations.readWhatTheControlMeansHowTo")); },
  get 'help-search-track'() { return card(msg("explanations.whereToShowTheSetting"), msg("explanations.chooseTheTrackInWhichToLocate")); },
  get 'help-search-show'() { return card(msg("explanations.goToTheSetting"), msg("explanations.openTheRelevantSectionAndHighlightThe"), msg("explanations.forPortamentoFirstEnableNewNotesCutting")); },
  get 'help-search-guide'() { return card(msg("explanations.launchTheRelatedGuide"), msg("explanations.closeSearchAndOpenAStepBy")); },
  get 'help-search-close'() { return card(msg("explanations.closeSearch"), msg("explanations.returnToTheWorkspaceEscapeAlsoCloses")); },
  get 'help-search-arrival'() { return card(msg("explanations.searchDestination"), msg("explanations.highlightTheControlOrItsNearestAvailable")); },
  get 'wave-motion'() { return card(msg("explanations.moveThroughWavetableFrames"), msg("explanations.startSetsTheInitialFrameBlendScan"), msg("explanations.forRhythmicBassTryStartAt10")); },
  get 'wave-scan-mode'() { return card(msg("explanations.onePassOrPingPong"), msg("explanations.onePassMovesFromTheStartPosition"), msg("explanations.theScanIsLimitedByTableEdges")); },
  get 'wave-scan-cycles'() { return card(msg("explanations.cyclesPerNote"), msg("explanations.oneCycleTravelsFromScanStartTo"), msg("explanations.chooseFourCyclesAndANoteDuration")); },
  get 'wave-position-lfo'() { return card(msg("explanations.positionLFO"), msg("explanations.aSlowControlWaveformMovesTheFrame"), msg("explanations.forMovementAroundTheMiddleSetStart")); },
  get 'wave-lfo-shape'() { return card(msg("explanations.lfoWaveform"), msg("explanations.sineSlowsSmoothlyNearItsExtremesTriangle"), msg("explanations.sineSuitsSoftPadsTriangleSuitsRhythmic")); },
  get 'wave-lfo-rate'() { return card(msg("explanations.lfoRate"), msg("explanations.completeOscillationsPerSecondFrom005"), msg("explanations.lowRatesCreateGradualDevelopmentHighRates")); },
  get 'wave-lfo-depth'() { return card(msg("explanations.lfoAmount"), msg("explanations.deviationInEitherDirectionFromTheCurrent"), msg("explanations.positionIsClampedAtTheEdgesExcessive")); },
  get 'wave-lfo-phase'() { return card(msg("explanations.lfoStartingPhase"), msg("explanations.phaseChoosesWhereTheCycleBegins0"), msg("explanations.differentPhasesAcrossLayersSeparateTheirTimbral")); },
  get 'scene-tempo'() { return card(msg("explanations.sceneEntryTempo"), msg("explanations.sharedUsesTheProjectSBPMAnd"), msg("explanations.chooseCustomAndEnterAValueEnter")); },
  get 'chain-scene'() { return card(msg("explanations.sceneAtThisPosition"), msg("explanations.chooseWhichScenePlaysAtThisPosition"), msg("explanations.repeatASceneInSeveralTilesWith")); },
  get 'chain-order'() { return card(msg("explanations.playbackOrder"), msg("explanations.theNumberMarksThisEntrySSequence"), msg("explanations.dragTheDottedHandleOnTheLeft")); },
  get 'chain-bars'() { return card(msg("explanations.entryDuration"), msg("explanations.howManyBarsThisSceneEntryPlays"), msg("explanations.lengthenForDevelopmentOrShortenForA")); },
  get 'chain-remove'() { return card(msg("explanations.removeAnEntry"), msg("explanations.removeOnlyThisOccurrenceFromTheSequence"), msg("explanations.ctrlZRestoresTheDeletedTile")); },
  get 'chain-add'() { return card(msg("explanations.addAnEntry"), msg("explanations.appendATileUsingTheFirstScene"), msg("explanations.chooseTheSceneDurationAndOptionalCustom")); },
  get "undo"() { return card(msg("explanations.undoAnEdit"), msg("explanations.restoreTheProjectToItsStateBefore"), msg("explanations.ctrlZDoesTheSameCtrlShift")); },
  get "redo"() { return card(msg("explanations.redoAnEdit"), msg("explanations.restoreTheLastUndoneActionANew"), msg("explanations.pressTheButtonOrCtrlShiftZ")); },
  get "scene-name"() { return card(msg("explanations.sceneName"), msg("explanations.nameASectionOfThePieceSuch"), msg("explanations.useAShortNameThatIsEasy")); },
  get "scene-mode"() { return card(msg("explanations.playOneScene"), msg("explanations.loopTheSelectedSceneWithoutAutomaticallyAdvancing"), msg("explanations.useThisWhileWorkingOnOneSection")); },
  get "chain-mode"() { return card(msg("explanations.playTheSceneSequence"), msg("explanations.playScenesInTheOrderAndDurations"), msg("explanations.openSequenceArrangeTheSectionsAndStart")); },
  get "fold-open"() { return card(msg("explanations.expandATrack"), msg("explanations.openThisTrackSEditorCollapsingSaves"), msg("explanations.expandToEditNotesOrSettingsThe")); },
  get "wave-quality"() { return card(msg("explanations.wavefoldingQuality"), msg("explanations.4OversamplingReducesWavefoldingAliasingByProcessing"), msg("explanations.keep4ForBrightSoundsCompareWith")); },
  get "operator-shape"() { return card(msg("explanations.operatorWaveform"), msg("explanations.waveformOfOneSoundComponentSineIs"), msg("explanations.combineShapesAndFrequencyRatiosToBuild")); },
  get "operator-ratio"() { return card(msg("explanations.operatorFrequencyRatio"), msg("explanations.frequencyOfThisComponentRelativeToThe"), msg("explanations.try12And3ForA")); },
  get "operator-level"() { return card(msg("explanations.operatorLevel"), msg("explanations.thisComponentSContributionToTheSum"), msg("explanations.changeItGraduallyModulationCanQuicklyAdd")); },
  get "operator-route"() { return card(msg("explanations.operatorRouting"), msg("explanations.sendThisRowToTheOutputOr"), msg("explanations.chooseADestinationOperatorForMetallicOr")); },
  get "operator-add"() { return card(msg("explanations.addAnOperator"), msg("explanations.addAComponentToTheWaveformTable"), msg("explanations.setItsFrequencyLevelAndShapeAudition")); },
  get "operator-delete"() { return card(msg("explanations.removeAnOperator"), msg("explanations.removeTheSelectedWaveformComponent"), msg("explanations.listenForTheOvertoneThatDisappearsThis")); },
  get "wave-view"() { return card(msg("explanations.graphZoomAndPosition"), msg("explanations.theseButtonsZoomAndMoveTheVisible"), msg("explanations.allShowsTheCompleteWaveformZoomInto")); },
  get "wave-frame"() { return card(msg("explanations.editedFrame"), msg("explanations.chooseAWaveformFrameToViewAnd"), msg("explanations.makeFramesDifferentThenSetStartAnd")); },
  get "wave-frame-shape"() { return card(msg("explanations.frameShapePreset"), msg("explanations.replaceTheSelectedFrameWithSineTriangle"), msg("explanations.startWithASimpleShapeAndDraw")); },
  get "wave-frame-add"() { return card(msg("explanations.duplicateAFrame"), msg("explanations.appendACopyOfTheSelectedFrame"), msg("explanations.editTheCopySoScanningBlendsBetween")); },
  get "wave-frame-delete"() { return card(msg("explanations.deleteAFrame"), msg("explanations.removeTheSelectedFrameAtLeastTwo"), msg("explanations.removeRedundantSimilarShapesToMakeThe")); },
  get "wave-position"() { return card(msg("explanations.initialWavetablePosition"), msg("explanations.theBlendBetweenTheFirstAndLast"), msg("explanations.zeroIsTheFirstFrame100Is")); },
  get "wave-sweep"() { return card(msg("explanations.wavetableScan"), msg("explanations.distanceFromTheInitialToFinalPosition"), msg("explanations.startAt0WithA100Scan")); },
  get "mseg-point"() { return card(msg("explanations.envelopePoint"), msg("explanations.aPointSetsTheSelectedTargetS"), msg("explanations.selectAPointDragItOrEnter")); },
  get "mseg-time"() { return card(msg("explanations.pointTime"), msg("explanations.positionWithinTheShapeInPercentWithout"), msg("explanations.moveAnAttackEarlierOrCreateA")); },
  get "mseg-level"() { return card(msg("explanations.pointAmplitude"), msg("explanations.voiceAmplitudeAtThisMomentZeroIs"), msg("explanations.highPointsFollowingLowOnesCreateRepeated")); },
  get "mseg-add"() { return card(msg("explanations.addAPoint"), msg("explanations.insertAPointHalfwayThroughTheLongest"), msg("explanations.youCanAlsoDoubleClickTheDesired")); },
  get "mseg-delete"() { return card(msg("explanations.deleteAPoint"), msg("explanations.removeTheSelectedInteriorPointAndConnect"), msg("explanations.simplifyTheShapeCtrlZRestoresThe")); },
  get "zone-low"() { return card(msg("explanations.zoneMinimumFrequency"), msg("explanations.lowestNoteFrequencyThatSelectsThisRecording"), msg("explanations.combineWithTheUpperBoundaryToSplit")); },
  get "zone-high"() { return card(msg("explanations.zoneMaximumFrequency"), msg("explanations.upperEdgeOfThisRecordingSFrequency"), msg("explanations.alignNeighboringZoneBoundariesSoNotesSelect")); },
  get "zone-velocity-low"() { return card(msg("explanations.minimumNoteVelocity"), msg("explanations.lowerVelocityBoundaryForThisZoneFrom"), msg("explanations.useSeparateZonesForSoftAndAccented")); },
  get "zone-velocity-high"() { return card(msg("explanations.maximumNoteVelocity"), msg("explanations.upperVelocityBoundaryForThisZoneFrom"), msg("explanations.togetherWithTheLowerBoundaryDeterminesWhich")); },
  get "zone-recording"() { return card(msg("explanations.zoneRecording"), msg("explanations.samplePlayedWhenANoteMatchesThis"), msg("explanations.chooseALibraryRecordingAndCheckIts")); },
  get "zone-up"() { return card(msg("explanations.moveAZoneUp"), msg("explanations.changeZoneSelectionPriorityTheFirstMatching"), msg("explanations.placeAMoreSpecificZoneBeforeA")); },
  get "zone-delete"() { return card(msg("explanations.deleteAZone"), msg("explanations.removeTheRecordingSelectionRuleTheSample"), msg("explanations.notesWillUseAnotherMatchingZoneOr")); },
  get "zone-add"() { return card(msg("explanations.addAZone"), msg("explanations.createANewPlayingRangeForA"), msg("explanations.chooseASampleSetFrequencyAndVelocity")); },
  get "round-robin"() { return card(msg("explanations.roundRobinRecordings"), msg("explanations.consecutiveNotesInTheZoneCycleThrough"), msg("explanations.addSimilarHitsToCreateANatural")); },
  get "variant-up"() { return card(msg("explanations.earlierInTheRotation"), msg("explanations.moveThisRecordingOnePlaceEarlierIn"), msg("explanations.reorderRecordingsToGetTheDesiredAccent")); },
  get "variant-delete"() { return card(msg("explanations.removeAVariation"), msg("explanations.removeTheRecordingFromThisZoneS"), msg("explanations.useThisWhenOneVariationStandsOut")); },
  get "bridge-code"() { return card(msg("explanations.assistantConnectionCode"), msg("explanations.aSessionSecretLinksThisTabTo"), msg("explanations.obtainTheCodeWithYourAgentS")); },
  get "bridge-write"() { return card(msg("explanations.allowAssistantEdits"), msg("explanations.allowTheConnectedAgentToChangeThe"), msg("explanations.chooseThePermissionThenConnectToApply")); },
  get "bridge-transport"() { return card(msg("explanations.allowPlaybackControl"), msg("explanations.allowTheAgentToStartAndStop"), msg("explanations.setThisSeparatelyFromEditingPermissionThen")); },
  get "bridge-connect"() { return card(msg("explanations.connectAnAgent"), msg("explanations.validateTheCodeAndConnectWithThe"), msg("explanations.connectAgainAfterChangingPermissions")); },
  get "bridge-disconnect"() { return card(msg("explanations.disconnectAnAgent"), msg("explanations.closeTheConnectionAndRemoveTheCode"), msg("explanations.useAfterWorkingTogetherOrWhenChanging")); },
  get "preset-apply"() { return card(msg("explanations.chooseAnInstrument"), msg("explanations.applyThisSoundToTheSelectedTarget"), msg("explanations.auditionItFirstWithPlayThenClick")); },
  get "favorite"() { return card(msg("explanations.favoriteSound"), msg("explanations.theStarAddsOrRemovesAFavorite"), msg("explanations.starSoundsYouLikeAndUseFavorites")); },
  get "library-width"() { return card(msg("explanations.instrumentBrowserWidth"), msg("explanations.giveLongNamesMoreRoomOrFree"), msg("explanations.dragThePanelSRightEdgeUse")); },
  get "preset-rename"() { return card(msg("explanations.renameAnInstrument"), msg("explanations.thePencilChangesItsNameInThe"), msg("explanations.enterANameAndSaveEscapeCancels")); },
  get "preset-delete"() { return card(msg("explanations.deleteASavedPreset"), msg("explanations.removeASavedSoundFromMyInstruments"), msg("explanations.removeAnUnwantedStartingPointToKeep")); },
  get "library-category"() { return card(msg("explanations.soundCategory"), msg("explanations.groupSimilarInstrumentsSuchAsDrumsBasses"), msg("explanations.clickTheHeadingToCollapseOrExpand")); },
  get "library-pack"() { return card(msg("explanations.instrumentCollections"), msg("explanations.groupSoundsByMusicalRoleRhythmBass"), msg("explanations.combineACollectionWithSearchAndFavorites")); },
  get "favorites-only"() { return card(msg("explanations.favoritesOnly"), msg("explanations.showSoundsMarkedWithAStar"), msg("explanations.turnThisFilterOffToSeeThe")); },
  get "filters-reset"() { return card(msg("explanations.resetFilters"), msg("explanations.clearTheQueryCollectionSelectionAndFavorites"), msg("explanations.usefulWhenASoundUnexpectedlyDisappearsFrom")); },
  get "search-clear"() { return card(msg("explanations.clearSearch"), msg("explanations.removeTheQueryWhileKeepingOtherFilters"), msg("explanations.useThisToStartANewSearch")); },
  get "panel-close"() { return card(msg("explanations.hideAPanel"), msg("explanations.closeThisPanelToFreeSpaceSettings"), msg("explanations.reopenThePanelUsingItsButtonOr")); },
  get "track-delete"() { return card(msg("explanations.deleteATrack"), msg("explanations.removeTheTrackAndItsClipsFrom"), msg("explanations.useForAnUnwantedInstrumentForTemporary")); },
  get "sample-reverse"() { return card(msg("explanations.reversePlayback"), msg("explanations.playTheSelectedRegionBackwardInDirect"), msg("explanations.tryAHitOrNoiseTailTo")); },
  get "sample-loop"() { return card(msg("explanations.loopForNoteDuration"), msg("explanations.repeatTheSelectedRegionWhileTheNote"), msg("explanations.adjustStartEndAndLoopCrossfadeFor")); },
  get "slice-selection"() { return card(msg("explanations.saveSelectionAsASlice"), msg("explanations.addTheSelectedWaveformRegionToThe"), msg("explanations.selectAHitOrSyllableThenPress")); },
  get "slice-count"() { return card(msg("explanations.equalSliceCount"), msg("explanations.numberOfRegionsCreatedWhenSlicingThe"), msg("explanations.chooseACountThatSuitsTheMaterial")); },
  get "slice-all"() { return card(msg("explanations.sliceTheWholeRecording"), msg("explanations.addTheChosenNumberOfEqualSlices"), msg("explanations.afterSlicingRefineEachHitSBoundaries")); },
  get "slice-pattern"() { return card(msg("explanations.clipFromSlices"), msg("explanations.createANotePatternThatPlaysThe"), msg("explanations.reorderRemoveOrRepeatNotesToCreate")); },
  get "slice-name"() { return card(msg("explanations.sliceName"), msg("explanations.aShortLabelForTheRecordingRegion"), msg("explanations.nameItAfterItsContentSuchAs")); },
  get "slice-start"() { return card(msg("explanations.sliceStart"), msg("explanations.startTimeWithinTheOriginalFileIn"), msg("explanations.adjustItSoTheNoteBeginsAt")); },
  get "slice-end"() { return card(msg("explanations.sliceEnd"), msg("explanations.endTimeWithinTheOriginalFileIn"), msg("explanations.trimAnUnwantedTailOrLeaveMore")); },
  get "slice-preview"() { return card(msg("explanations.auditionASlice"), msg("explanations.playOnlyTheSelectedRecordingRegionTo"), msg("explanations.auditionAfterChangingStartOrEndBefore")); },
  get "slice-delete"() { return card(msg("explanations.deleteASlice"), msg("explanations.removeTheSliceDefinitionWhileKeepingThe"), msg("explanations.checkNotesUsingTheSliceCtrlZ")); },
  get workspace() { return card(msg("explanations.workspace"), msg("explanations.buildMusicFromTracksEachWithAn"), msg("explanations.startWithTrackChooseASoundAnd"), msg("explanations.forIDMTryDifferentCycleLengthsA")); },
  get 'point-help'() { return card(msg("explanations.whatSThis"), msg("explanations.enableTheHelpCursorWhileActiveClicks"), msg("explanations.pressOrF1ThenSelectAnElement")); },
  get 'help-guides'() { return card(msg("explanations.taskGuides"), msg("explanations.stepByStepPathsForBuildingA"), msg("explanations.chooseATaskAndFollowTheHighlight")); },
  get macros() { return card(msg("explanations.macros"), msg("explanations.oneKnobMovesSeveralInstrumentPropertiesTogether"), msg("explanations.addAMacroOpenAssignmentsChooseParameters"), msg("explanations.aTensionMacroCouldOpenTheFilter")); },
  get 'macro-tile'() { return card(msg("explanations.oneMacro"), msg("explanations.theTileGroupsAKnobAndAll"), msg("explanations.dragVerticallyToTurnTheKnobDouble")); },
  get 'macro-value'() { return card(msg("explanations.macroPosition"), msg("explanations.50IsTheBaseSoundMovingToward"), msg("explanations.dragUpOrDownShiftSlowsMovement"), msg("explanations.turnASoftBassBrightAndRough")); },
  get 'macro-bindings'() { return card(msg("explanations.macroAssignments"), msg("explanations.parametersControlledByThisKnobLinkUp"), msg("explanations.chooseAParameterAndSetItsAmount")); },
  get 'macro-binding'() { return card(msg("explanations.parameterBinding"), msg("explanations.oneAssignmentLinksThisMacroToAn"), msg("explanations.chooseTheSoundPropertyOnTheLeft")); },
  get 'macro-target'() { return card(msg("explanations.assignmentTarget"), msg("explanations.chooseWhichSoundPropertyFollowsTheMacro"), msg("explanations.selectAParameterThenCheckItsAmount"), msg("explanations.linkOneMacroToFilterBrightnessAnd")); },
  get 'macro-depth'() { return card(msg("explanations.assignmentAmount"), msg("explanations.howFarTheParameterDeviatesFromIts"), msg("explanations.doubleClickForNumericInputLogarithmicParameters"), msg("explanations.a03SDecayAmountLengthens")); },
  get 'macro-center'() { return card(msg("explanations.centerTheMacro"), msg("explanations.setTheKnobTo50SoIts"), msg("explanations.compareWithTheBaseSoundWithoutDeleting")); },
  get 'macro-name'() { return card(msg("explanations.macroName"), msg("explanations.describeTheAudibleResultRatherThanNecessarily"), msg("explanations.useAShortNameSuchAsWarmth")); },
  get 'macro-add'() { return card(msg("explanations.addAMacro"), msg("explanations.createACenteredKnobAssignedToThe"), msg("explanations.expandAssignmentsNameTheMacroAndChoose")); },
  get 'macro-defaults'() { return card(msg("explanations.threeStarterMacros"), msg("explanations.addBrightnessLengthAndWidthControllingThe"), msg("explanations.useThemAsStartingPointsAndAdjust")); },
  get 'macro-add-binding'() { return card(msg("explanations.addAnAssignment"), msg("explanations.linkAnotherParameterToThisMacroUp"), msg("explanations.chooseAPropertyAndAmountInThe")); },
  get 'macro-remove-binding'() { return card(msg("explanations.removeAnAssignment"), msg("explanations.removeOneParameterBindingTheMacroAnd"), msg("explanations.useWhenAPropertyShouldNoLonger")); },
  get 'macro-delete'() { return card(msg("explanations.deleteAMacro"), msg("explanations.removeTheKnobAndAllItsAssignments"), msg("explanations.baseInstrumentParametersRemainCtrlZRestores")); },
  get 'layer-base'() { return card(msg("explanations.mainVoice"), msg("explanations.theInstrumentSFirstSoundItsSource"), msg("explanations.lowerItsLevelToBlendWithAdditional")); },
  get 'layer-edit'() { return card(msg("explanations.additionalVoiceSettings"), msg("explanations.openThisLayerSSourceSelectionAnd"), msg("explanations.clickTheNameToChooseASound")); },
  get 'layer-gain'() { return card(msg("explanations.voiceLevel"), msg("explanations.thisVoiceSContributionToTheInstrument"), msg("explanations.balanceVoicesWhileListeningToTheComplete"), msg("explanations.keepAFullBassAsTheMain")); },
  get 'layer-ratio'() { return card(msg("explanations.layerFrequencyRatio"), msg("explanations.multiplyEachNoteSFrequencyForThis"), msg("explanations.enterAMultiplierThisIsNotTempo"), msg("explanations.15AddsAFifth1013")); },
  get 'layer-add'() { return card(msg("explanations.addAVoiceFromAPreset"), msg("explanations.copyTheSelectedPresetSMainVoice"), msg("explanations.chooseAFactoryOrSavedSoundThen")); },
  get 'layer-source'() { return card(msg("explanations.replaceALayerSSound"), msg("explanations.replaceThisLayerSSourceAndSound"), msg("explanations.startFromAPresetThenEditSource")); },
  get 'layer-delete'() { return card(msg("explanations.deleteALayer"), msg("explanations.removeThisAdditionalVoiceTheMainVoice"), msg("explanations.ctrlZRestoresTheLayerAndIts")); },
  get attack() { return card(msg("explanations.attack"), msg("explanations.timeForAmplitudeToRiseFromSilence"), msg("explanations.reduceForSharpHitsOrIncreaseFor"), msg("explanations.try15MsForAClick")); },
  get sustain() { return card(msg("explanations.peakHold"), msg("explanations.fractionOfTheRemainingTimeAfterAttack"), msg("explanations.0StartsDecayImmediatelyHigherValuesHold"), msg("explanations.shortHoldSuitsPercussionLongHoldSuits")); },
  get decay() { return card(msg("explanations.decay"), msg("explanations.fadeOutDurationOfTheSimpleEnvelope"), msg("explanations.shortValuesKeepTheSoundTightLong"), msg("explanations.shortDecaySeparatesRapidHitsLongDecay")); },
  get mono() { return card(msg("explanations.newNoteCutsOffPreviousVoices"), msg("explanations.aNewAttackStopsNotesAlreadySounding"), msg("explanations.enableWhenTailsClashSetPortamentoFor"), msg("explanations.makeABassLineClearerByKeeping")); },
  get 'choke-group'() { return card(msg("explanations.chokeGroup"), msg("explanations.tracksSharingAGroupNumberStopEach"), msg("explanations.assignTheSameNumberToRelatedSounds"), msg("explanations.aClosedHiHatCutsOffAn")); },
  get 'choke-priority'() { return card(msg("explanations.simultaneousAttackPriority"), msg("explanations.withinAChokeGroupChooseWhichTrack"), msg("explanations.giveAClosedHiHatHigherPriority")); },
  get portamento() { return card(msg("explanations.glidePortamento"), msg("explanations.smoothTransitionFromThePreviousNoteS"), msg("explanations.openTheTrackTabEnableNewNotes"), msg("explanations.try80150MsOnBassAlternating")); },
  get 'formant-group'() { return card(msg("explanations.formantsVowelLikeColor"), msg("explanations.emphasizedSpectralRegionsResemblingVocalTractResonances"), msg("explanations.addUpToFiveBandsAndSet"), msg("explanations.bandsAround800And1200HzCan")); },
  get 'formant-frequency'() { return card(msg("explanations.formantFrequency"), msg("explanations.centerOfTheSpectralRegionEmphasizedBy"), msg("explanations.moveItWhileListeningToABright")); },
  get 'formant-gain'() { return card(msg("explanations.formantLevel"), msg("explanations.strengthOfThisResonanceBlendedWithThe"), msg("explanations.increaseGraduallySeveralStrongBandsCanSound")); },
  get 'formant-add'() { return card(msg("explanations.addAFormant"), msg("explanations.addAnotherResonantBandBandsTogetherCreate"), msg("explanations.setFrequencyAndLevelUpToFive")); },
  get 'formant-delete'() { return card(msg("explanations.removeAFormant"), msg("explanations.removeOneResonantBandLeavingTheRemaining"), msg("explanations.compareByEarCtrlZRestoresThe")); },
  get 'dialog'() { return card(msg("explanations.actionDialog"), msg("explanations.configureTheCurrentOperationAndConfirmIts"), msg("explanations.readTheTitleAndConditionsCancelCloses")); },
  get 'dialog-cancel'() { return card(msg("explanations.cancelTheAction"), msg("explanations.closeThisDialogWithoutPerformingTheProposed"), msg("explanations.useWhenYouWantToReturnTo")); },
  get 'dialog-confirm'() { return card(msg("explanations.confirmTheAction"), msg("explanations.performTheOperationDescribedByThisDialog"), msg("explanations.checkTheEnteredNameAndConditionsBefore")); },
  get 'status'() { return card(msg("explanations.audioStatus"), msg("explanations.showsEngineReadinessResourceUsageAndLimit"), msg("explanations.ifNotesAreDroppedReduceUnisonLayers")); },
  get 'bridge'() { return card(msg("explanations.externalAssistant"), msg("explanations.optionallyConnectAnAIAssistantOnThis"), msg("explanations.configureBarlowMCPInTheAssistantThen")); },
  get 'sample-zones'() { return card(msg("explanations.samplerZones"), msg("explanations.useDifferentRecordingsForDifferentFrequenciesOr"), msg("explanations.addAZoneChooseItsRecordingSet"), msg("explanations.softAndStrongHitsCanUseDifferent")); },
  get 'export-wav'() { return card(msg("explanations.exportAudioToWAV"), msg("explanations.renderASceneOrSequenceToAn"), msg("explanations.chooseDurationAndTailModeNaturalPreserves")); },
};
