import { t as msg } from '../i18n/runtime.ts';
import { PARAMETERS, type ParameterId } from '../parameters';
import type { HelpCard } from './cards';
// Exhaustive: adding a numeric parameter requires writing its explanation.
const descriptions: Record<ParameterId, string> = {
  get 'instrument.ringMix'() { return msg("parameterHelp.ringModulationMixMultiplyTheSourceBy"); },
  get 'instrument.ringRatio'() { return msg("parameterHelp.frequencyOfTheExtraWaveformRelativeTo"); },
  get 'instrument.foldDrive'() { return msg("parameterHelp.wavefoldingAmountPeaksFoldInwardCreatingNew"); },
  get 'instrument.combMix'() { return msg("parameterHelp.combFilterMixVeryShortRepeatsEmphasize"); },
  get 'instrument.combHz'() { return msg("parameterHelp.combFilterFrequencyControlsTheSpacingOf"); },
  get 'instrument.combFeedback'() { return msg("parameterHelp.amountFedBackIntoTheShortComb"); },
  get 'track.portamentoSec'() { return msg("parameterHelp.timeToGlideToTheNextSingle"); },
  get 'effect.mix'() { return msg("parameterHelp.balanceOfDryAndProcessedSoundZero"); },
  get 'effect.timeSec'() { return msg("parameterHelp.timeBeforeTheEchoRepeatsShortValues"); },
  get 'effect.feedback'() { return msg("parameterHelp.fractionOfTheEchoFedBackFor"); },
  get 'patch.bpm'() { return msg("parameterHelp.tempoInBeatsPerMinuteSpeedsUp"); },
  get 'patch.masterVolume'() { return msg("parameterHelp.finalProjectLevelAfterTheTracksAre"); },
  get 'track.volume'() { return msg("parameterHelp.trackLevelAcrossAllScenesUseIt"); },
  get 'track.pan'() { return msg("parameterHelp.trackPositionBetweenTheLeftAndRight"); },
  get 'track.freq'() { return msg("parameterHelp.trackTuningSRootFrequencyInHertz"); },
  get 'track.phase'() { return msg("parameterHelp.trackCycleOffsetInStepsRelativeTo"); },
  get 'track.noteSteps'() { return msg("parameterHelp.durationOfNewlyDrawnNotesInThis"); },
  get 'pattern.volume'() { return msg("parameterHelp.clipLevelMultipliedByTheTrackS"); },
  get 'pattern.rate'() { return msg("parameterHelp.durationOfOneClipStepRelativeTo"); },
  get 'pattern.length'() { return msg("parameterHelp.numberOfStepsBeforeThePatternRepeats"); },
  get 'pattern.fadeIn'() { return msg("parameterHelp.fadeInTimeForThePartAnd"); },
  get 'pattern.fadeOut'() { return msg("parameterHelp.fadeOutTimeForThePartAnd"); },
  get 'instrument.attack'() { return msg("parameterHelp.timeForAmplitudeToRiseFromSilence"); },
  get 'instrument.decay'() { return msg("parameterHelp.decayDurationForTheSimpleEnvelopeWhen"); },
  get 'instrument.sustain'() { return msg("parameterHelp.proportionOfTimeAfterAttackHeldAt"); },
  get 'instrument.pitchDrop'() { return msg("parameterHelp.startingPitchAsAMultipleOfThe"); },
  get 'instrument.pitchTime'() { return msg("parameterHelp.timeToFallFromTheRaisedStarting"); },
  get 'instrument.filterLow'() { return msg("parameterHelp.lowerCutoffFrequenciesBelowItAreAttenuated"); },
  get 'instrument.filterFreq'() { return msg("parameterHelp.upperCutoffLowerValuesSoundDarkerAnd"); },
  get 'instrument.filterQ'() { return msg("parameterHelp.emphasisNearTheLowPassCutoffLow"); },
  get 'instrument.filterEnvAmount'() { return msg("parameterHelp.initialCutoffOffsetFromItsBaseValue"); },
  get 'instrument.filterEnvTime'() { return msg("parameterHelp.timeForCutoffToReturnToIts"); },
  get 'instrument.vibratoRate'() { return msg("parameterHelp.pitchOscillationsPerSecondSlowerRatesSound"); },
  get 'instrument.vibratoDepth'() { return msg("parameterHelp.pitchOscillationDepthInCents100Cents"); },
  get 'instrument.vibratoDelay'() { return msg("parameterHelp.timeForVibratoDepthToFadeIn"); },
  get 'instrument.unisonVoices'() { return msg("parameterHelp.numberOfNearlyIdenticalVoicesPlayingTogether"); },
  get 'instrument.unisonDetune'() { return msg("parameterHelp.pitchSpreadBetweenUnisonCopiesInCents"); },
  get 'instrument.unisonSpread'() { return msg("parameterHelp.stereoDistributionOfUnisonVoicesZeroCenters"); },
  get 'instrument.rootHz'() { return msg("parameterHelp.fundamentalFrequencyOfTheOriginalSamplePitched"); },
  get 'instrument.loopCrossfadeMs'() { return msg("parameterHelp.crossfadeBetweenTheSampleLoopSEnd"); },
  get 'instrument.sampleStart'() { return msg("parameterHelp.startOfTheSampleRegionInSeconds"); },
  get 'instrument.sampleEnd'() { return msg("parameterHelp.endOfTheSampleRegionInSeconds"); },
  get 'instrument.grainSizeMs'() { return msg("parameterHelp.durationOfOneGrainAShortFragment"); },
  get 'instrument.grainCount'() { return msg("parameterHelp.grainsEmittedPerNoteMoreMakesThe"); },
  get 'instrument.grainPos'() { return msg("parameterHelp.centerPositionOfTheGrainCloudWithin"); },
  get 'instrument.grainScatter'() { return msg("parameterHelp.howFarGrainsSpreadAroundTheCloud"); },
};
export function parameterHelp(id: ParameterId): HelpCard {
  return { title: PARAMETERS[id].label, text: descriptions[id], how: msg("parameterHelp.adjustByEarDoubleClickAKnob") };
}
