import assert from 'node:assert/strict';
import { DecodedAssets } from '../src/audio/decodedAssets.ts';
const limits={bytes:10,assetBytes:8,entries:3,pending:2};
const cache=new DecodedAssets(limits);
let calls=0, finish;
const a=cache.load('a',()=>{calls++;return new Promise(r=>finish=r);});
const duplicate=cache.load('a',async()=>{throw Error('duplicate decode');});
assert.equal(a,duplicate); await Promise.resolve();
let bStarted=false;
const b=cache.load('b',async()=>{bStarted=true;return {value:'B',bytes:4};});
await assert.rejects(cache.load('c',async()=>({value:'C',bytes:1})),/Очередь/);
assert.equal(bStarted,false);finish({value:'A',bytes:4});
assert.deepEqual(await Promise.all([a,duplicate,b]),['A','A','B']);
assert.equal(calls,1);assert.equal(cache.pending,0);
console.log('PASS deduplicated promise, serial decode, bounded pending queue');
const releaseA=cache.pin(['a','a']),releaseA2=cache.pin(['a']);
await cache.load('c',async()=>({value:'C',bytes:4}));
assert.equal(cache.get('b'),undefined);assert.equal(cache.get('a'),'A');assert.equal(cache.bytes,8);
releaseA();releaseA();
const releaseC=cache.pin(['c']);
await assert.rejects(cache.load('d',async()=>({value:'D',bytes:4})),/бюджет/);
assert.equal(cache.bytes,8);assert.equal(cache.get('c'),'C');assert.equal(cache.pending,0);
releaseA2();await cache.load('d',async()=>({value:'D',bytes:4}));
assert.equal(cache.get('a'),undefined);assert.equal(cache.get('c'),'C');releaseC();
console.log('PASS overlapping leases, idempotent release, pinned survival, atomic refusal and recovery');
await assert.rejects(cache.load('bad',async()=>({value:'X',bytes:NaN})),/Декодированный/);
await assert.rejects(cache.load('large',async()=>({value:'X',bytes:9})),/Декодированный/);
await assert.rejects(cache.load('fail',async()=>{throw Error('decode failure');}),/decode failure/);
assert.equal(await cache.load('fail',async()=>({value:'retry',bytes:2})),'retry');assert.equal(cache.bytes,10);
console.log('PASS invalid/oversize assets rejected, failed decode retry does not poison queue');
const small=new DecodedAssets({...limits,entries:1});
await small.load('a',async()=>({value:1,bytes:1}));await small.load('b',async()=>({value:2,bytes:1}));
assert.equal(small.size,1);assert.equal(small.bytes,1);assert.equal(small.get('a'),undefined);
console.log('PASS entry count is bounded independently of PCM bytes');
