import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { setTimeout as delay } from 'node:timers/promises';
import { chromium } from 'playwright-core';
const root = fileURLToPath(new URL('..', import.meta.url)), port = 5190;
const vite = spawn(process.execPath, [root + '/node_modules/vite/bin/vite.js', '--host', '127.0.0.1', '--port', String(port), '--strictPort'], { cwd: root, stdio: 'ignore' });
let browser;
try {
  for (let i = 0; i < 60; i++) { if (vite.exitCode !== null) throw new Error('Vite exited'); try { if ((await fetch(`http://127.0.0.1:${port}`)).ok) break; } catch {} await delay(250); }
  browser = await chromium.launch({ executablePath: process.env.BARLOW_BROWSER ?? 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.addInitScript(() => localStorage.setItem('barlow.onboarding.v1', JSON.stringify({ invited: true, seen: { main: true } })));
  await page.goto(`http://127.0.0.1:${port}`);
  const fxRows = page.locator('[data-ob="fx-list"]').first().locator('[data-fx-id]');
  await page.locator('[data-ob="mode-track"]').first().click();
  while (await fxRows.count() < 2) await page.locator('[data-ob="fx-add"]').first().click();
  const first = await fxRows.nth(0).getAttribute('data-fx-id'), second = await fxRows.nth(1).getAttribute('data-fx-id');
  assert.notEqual(first, second);
  await page.locator('[data-ob="mode-sketch"]').first().click();
  await page.locator('[data-ob="auto-toggle"]').first().click();
  await page.getByRole('button', { name: 'микс эффекта', exact: true }).first().click();
  const selector = page.getByRole('combobox', { name: 'Эффект автоматизации', exact: true }).first();
  await selector.selectOption(second);
  await page.locator('[data-ob="mods-add"]').first().click();
  await page.waitForFunction(id => JSON.parse(localStorage.getItem('barlow.patch.v12') ?? '{}').tracks?.[0].patterns?.[0].mods?.some(m => m.target === 'fxMix' && m.fxId === id), second);
  console.log('PASS modulation targets selected effect rather than first list position');
  const lane = page.locator('svg.auto-lane').first();
  await lane.click({ position: { x: 40, y: 20 } });
  await lane.click({ position: { x: 200, y: 40 } });
  await page.waitForFunction(id => JSON.parse(localStorage.getItem('barlow.patch.v12')).tracks[0].patterns[0].automation?.some(c => c.fxId === id && c.points.length === 2), second);
  const point = lane.locator('.env-handle').first();
  const original = await point.getAttribute('aria-valuenow');
  await point.focus(); await point.press('ArrowUp');
  assert.notEqual(await point.getAttribute('aria-valuenow'), original);
  await page.keyboard.press('Control+z'); assert.equal(await point.getAttribute('aria-valuenow'), original);
  const box = await point.boundingBox();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2 + 30, box.y + box.height / 2 + 15, { steps: 8 }); await page.mouse.up();
  assert.notEqual(await point.getAttribute('aria-valuenow'), original);
  await page.keyboard.press('Control+z'); assert.equal(await point.getAttribute('aria-valuenow'), original);
  console.log('PASS automation keyboard editing and one-step undo for full pointer drag');
  await page.locator('[data-ob="mode-track"]').first().click();
  await page.getByRole('button', { name: 'Эффект 2 вверх', exact: true }).first().click();
  assert.equal(await fxRows.first().getAttribute('data-fx-id'), second);
  await page.waitForFunction(id => JSON.parse(localStorage.getItem('barlow.patch.v12')).tracks[0].effects[0].id === id, second);
  const afterReorder = await page.evaluate(() => JSON.parse(localStorage.getItem('barlow.patch.v12')).tracks[0]);
  assert.equal(afterReorder.patterns[0].automation[0].fxId, second);
  assert.equal(afterReorder.patterns[0].mods[0].fxId, second);
  console.log('PASS keyboard FX reorder preserves curve and modulation identity');
  await fxRows.first().getByTitle('Убрать эффект', { exact: true }).click();
  await page.locator('[data-ob="mode-sketch"]').first().click();
  await page.getByText('Цель удалена — назначения не звучат.', { exact: true }).waitFor();
  assert.equal(await selector.inputValue(), second);
  await page.keyboard.press('Control+z');
  await page.waitForFunction(id => JSON.parse(localStorage.getItem('barlow.patch.v12')).tracks[0].effects.some(e => e.id === id), second);
  console.log('PASS deleted FX assignments remain explicit and undo restores them');
  await page.reload();
  await page.locator('[data-ob="mode-sketch"]').first().click();
  await page.locator('[data-ob="auto-toggle"]').first().click();
  await page.getByRole('button', { name: 'микс эффекта', exact: true }).first().click();
  await selector.selectOption(second);
  const state = await page.evaluate(() => JSON.parse(localStorage.getItem('barlow.patch.v12')).tracks[0]);
  assert.equal(state.patterns[0].automation[0].fxId, second);
  assert.equal(state.effects[0].id, second);
  await page.screenshot({ path: root + '/tmp/fx-automation.png' });
  assert.deepEqual(errors, []);
  console.log('PASS FX references survive save and reload');
  console.log('fx-ui: PASS');
} finally { await browser?.close(); vite.kill(); }
