import assert from 'node:assert/strict';
import { createHistory, reduceHistory } from '../src/history.ts';
import { parseRatio, parameterAt } from '../src/parameters.ts';

const h = createHistory(0);
let calls = 0;
h.set(v => { calls++; return v + 1; });
assert.equal(calls, 1);
h.begin('drag');
for (let i = 2; i < 200; i++) h.set(i);
h.commit('drag');
assert.deepEqual(h.snapshot().past, [0, 1]);
h.undo(); assert.equal(h.snapshot().present, 1);
h.redo(); assert.equal(h.snapshot().present, 199);
h.undo(); h.begin('field'); h.set(50); h.cancel('field');
assert.equal(h.snapshot().present, 1);
h.redo(); assert.equal(h.snapshot().present, 199);
h.begin('field'); h.set(300); h.step(400);
assert.deepEqual(h.snapshot().past.slice(-2), [199, 300]);
h.cancel('field'); assert.equal(h.snapshot().present, 400);
h.begin('untouched'); h.commit();
assert.equal(h.snapshot().past.at(-1), 300);
h.begin('draft'); h.set(900); h.undo();
assert.equal(h.snapshot().present, 400);
for (let i = 0; i < 200; i++) h.step(i);
assert.equal(h.snapshot().past.length, 100);
const before = Object.freeze({ present: 1, past: Object.freeze([0]), future: Object.freeze([]), gesture: null });
const a = reduceHistory(before, { type: 'set', value: 2 });
const b = reduceHistory(before, { type: 'set', value: 2 });
assert.deepEqual(a, b);
assert.equal(before.present, 1);
console.log('history: PASS (single evaluation, explicit gestures, cancel/redo, discrete boundaries, pure reducer, limit)');
assert.equal(parseRatio('7/5'), 1.4);
assert.equal(parseRatio(' 0,75 '), 0.75);
assert.equal(parseRatio('.5'), 0.5);
assert.equal(parseRatio('1/0'), null);
assert.equal(parseRatio('1;alert(1)'), null);
assert.equal(parseRatio('33'), null);
assert.equal(parameterAt('instrument.unisonVoices', 0.5), 5);
assert.ok(Math.abs(parameterAt('instrument.filterFreq', 0.5) - Math.sqrt(60 * 12000)) < 1e-6);
console.log('parameters: PASS (rational steps, bounded input, musical logarithmic mapping)');
