import assert from 'node:assert/strict';
import {copySelection,moveSelection,pasteNotes} from '../src/music/noteEdits.ts';
const a={n:0,vel:.7,prob:.8,len:2,ratchet:4,microTimingMs:-15,locks:{decay:.4,unisonVoices:3},sliceId:'cut-1'};
const b={n:1,vel:.4,prob:1,len:.5};
const steps=[{notes:[a]},{notes:[]},{notes:[b]},{notes:[]}],sel=new Set(['0:0','9:99']);
const copied=copySelection(steps,sel);assert.equal(copied.length,1);assert.deepEqual(copied[0],{...a,col:0});
copied[0].locks.decay=.9;assert.equal(a.locks.decay,.4);
const moved=moveSelection(steps,new Set(['0:0']),1,1,3);
assert.deepEqual(moved.steps[1].notes[0],{...a,n:1});assert.equal(moved.steps[0].notes.length,0);assert.equal(steps[0].notes[0],a);
const blocked=moveSelection(steps,new Set(['0:0']),2,1,3);assert.equal(blocked.steps,steps);assert.equal(blocked.blocked,true);
const pasted=pasteNotes(steps,copySelection(steps,new Set(['0:0'])),3,3);assert.deepEqual(pasted.steps[3].notes[0],a);assert.notEqual(pasted.steps[3].notes[0].locks,a.locks);
assert.equal(pasteNotes(steps,[{...a,col:0},{...a,col:1}],3,3).skipped,1);
assert.equal(pasteNotes(steps,[{...a,col:0}],0,3).skipped,1);
const clamped=moveSelection(steps,new Set(['0:0']),100,100,3);assert.deepEqual(clamped.steps[3].notes[0],{...a,n:2});
console.log('PASS complete independent note copies, move/clamp, collision rollback, paste and skipped-note accounting');
const dense=Array.from({length:2048},()=>({notes:Array.from({length:64},(_,n)=>({...b,n}))}));
const all=new Set(dense.flatMap((s,c)=>s.notes.map(n=>`${c}:${n.n}`)));
assert.equal(moveSelection(dense,all,1,0,64).steps,dense);
assert.equal(pasteNotes(dense,copySelection(dense,all),0,64).skipped,131072);
console.log('PASS large selection within patch limits avoids argument-count overflow');
