import assert from 'node:assert/strict';
import { ByteLru } from '../src/audio/byteLru.ts';
import { ChainBudget, ChainBudgetError, emptyResources, estimateChainResources, resourcesFit, LIVE_CHAIN_LIMITS } from '../src/audio/chainBudget.ts';
const cache = new ByteLru(100, 3);
cache.set('a', 1, 40); cache.set('b', 2, 40); assert.equal(cache.get('a'), 1);
cache.set('c', 3, 40); assert.equal(cache.get('b'), undefined); assert.equal(cache.get('a'), 1); assert.equal(cache.bytes, 80);
cache.set('a', 4, 90); assert.equal(cache.bytes, 90); assert.equal(cache.size, 1);
cache.set('huge', 5, 101); assert.equal(cache.get('huge'), undefined); assert.equal(cache.bytes, 90);
cache.set('bad', 5, NaN); assert.equal(cache.bytes, 90);
console.log('PASS cache byte bound, LRU access, replacement accounting and oversize/NaN bypass');
const budget = new ChainBudget({ chains: 2, nodes: 100, bufferBytes: 1000 });
const a = {}, b = {}, c = {};
budget.reserve(a, { chains: 1, nodes: 30, bufferBytes: 400 }); budget.reserve(b, { chains: 1, nodes: 30, bufferBytes: 400 });
assert.throws(() => budget.reserve(c, { chains: 1, nodes: 1, bufferBytes: 1 }), ChainBudgetError);
assert.throws(() => budget.reserve(a, { chains: 1, nodes: 30, bufferBytes: 700 }), ChainBudgetError);
assert.deepEqual(budget.usage, {chains:2,nodes:60,bufferBytes:800});
budget.reserve(a, { chains: 1, nodes: 30, bufferBytes: 100 }); assert.equal(budget.usage.bufferBytes, 500);
budget.release(a); budget.release(a); budget.release(b); assert.deepEqual(budget.usage, emptyResources());
assert.throws(() => budget.reserve(c, {chains:1,nodes:NaN,bufferBytes:0}), ChainBudgetError);
assert.deepEqual(budget.usage, emptyResources());
console.log('PASS failed admission/resize atomic, shrink/release reuse capacity, double release and invalid costs');
assert.ok(!resourcesFit(estimateChainResources({effects:Array.from({length:16},()=>({type:'reverb',sizeSec:8,mix:1})),mods:[]}),LIVE_CHAIN_LIMITS));
assert.ok(resourcesFit(estimateChainResources({effects:[],mods:[]}),LIVE_CHAIN_LIMITS));
console.log('PASS one maximal effect stack rejected while a dry chain fits');
